# open_csv.py
# this class will be used to open the csv files generated by the simulation,
# and convert them into a format, which can be used to make the GasCel object, and the TrackMemory Object.

import csv
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from Results.Config import Config
from Results.track_memory import TrackMemory
from Results.raystate import Raystate

class CSVLoader:
    @staticmethod
    def load_config_from_csv(file_path):
        with open(file_path, mode='r') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                # Assuming the CSV has columns that match the Config fields
                config_data = {key: float(value) for key, value in row.items()}
                return Config(**config_data)  # Unpack dict to create Config object
        raise ValueError("No valid configuration found in CSV.")
    
    @staticmethod
    def load_track_memory_from_csv(file_path):
        track_memory = TrackMemory()
        with open(file_path, mode='r') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                # Assuming the CSV has columns that match the Raystate fields
                raystate_data = {key: float(value) for key, value in row.items()}
                raystate = Raystate(**raystate_data)  # Unpack dict to create Raystate object
                track_memory.add_state(raystate)
        return track_memory